# GENERATED by scripts/gen.py settings from settings.toml -- do not edit.
"""The server's settings, declared once in settings.toml.

load_settings() reads the environment at CALL time, never at import. Secrets are
SecretStr: they do not appear in repr(), in logs or in public_view(). A missing
or malformed setting raises SettingsError naming it -- never printing a value.
"""

from __future__ import annotations

import os
from collections.abc import Mapping

from pydantic import BaseModel, ConfigDict, SecretStr


class SettingsError(ValueError):
    """A setting is missing or malformed. Carries names, never values."""


class Settings(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)

    admit_race_window_ms: int = 0
    allow_dev_auth: bool = False
    as_of: str = ""
    database_url: SecretStr
    host: str = "127.0.0.1"
    migrate_database_url: SecretStr = SecretStr("")
    port: int = 8000
    static_dir: str = ""


# (ENV name, field, type, required, secret)
FIELDS: tuple[tuple[str, str, str, bool, bool], ...] = (
    ("ADMIT_RACE_WINDOW_MS", "admit_race_window_ms", "int", False, False),
    ("ALLOW_DEV_AUTH", "allow_dev_auth", "bool", False, False),
    ("AS_OF", "as_of", "str", False, False),
    ("DATABASE_URL", "database_url", "url", True, True),
    ("HOST", "host", "str", False, False),
    ("MIGRATE_DATABASE_URL", "migrate_database_url", "url", False, True),
    ("PORT", "port", "int", False, False),
    ("STATIC_DIR", "static_dir", "str", False, False),
)

_TRUE = frozenset({"1", "true", "yes", "on"})
_FALSE = frozenset({"0", "false", "no", "off", ""})


def _coerce(name: str, kind: str, raw: str) -> object:
    if kind == "int":
        try:
            return int(raw)
        except ValueError:
            raise SettingsError(f"{name}: expected an integer") from None
    if kind == "bool":
        word = raw.strip().lower()
        if word in _TRUE:
            return True
        if word in _FALSE:
            return False
        raise SettingsError(f"{name}: expected true or false")
    if kind == "url" and "://" not in raw:
        raise SettingsError(f"{name}: expected a URL")
    return raw


def load_settings(environ: Mapping[str, str] | None = None) -> Settings:
    env = os.environ if environ is None else environ
    values: dict[str, object] = {}
    missing: list[str] = []
    for name, field, kind, required, _secret in FIELDS:
        raw = env.get(name)
        if raw is None or (required and raw == ""):
            if required:
                missing.append(name)
            continue
        values[field] = _coerce(name, kind, raw)
    if missing:
        raise SettingsError("missing required setting(s): " + ", ".join(missing))
    return Settings.model_validate(values)


def public_view(settings: Settings) -> dict[str, object]:
    """Every non-secret setting, for logs and diagnostics."""
    return {
        name: getattr(settings, field)
        for name, field, _kind, _required, secret in FIELDS
        if not secret
    }
