"""Regenerate every derived artifact from its one declaration.

    uv run python scripts/gen.py <settings|contracts|concepts|registry|controls|all> [--check]

    settings   settings.toml -> src/__app__/settings.py, deploy/compose.env.yml,
               deploy/preflight_names.txt, frontend/src/gen/settings.ts
    contracts  contracts/wire.py + the composed root's route table ->
               wire/frozen.json, frontend/src/gen/types.ts, frontend/src/gen/client.ts
    concepts   concepts.toml -> frontend/src/gen/concepts.ts
    registry   contracts/registry.py -> frontend/src/gen/registry.ts
    controls   data-control attributes -> frontend/controls.json (node)

--check writes nothing and exits 1 naming every stale file (the `gen` lane).
The tests call the render_* functions directly, so "regenerating leaves no
diff" is checked on every backend run, not only in CI.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
import tomllib
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
for _path in (ROOT, ROOT / "src"):
    if str(_path) not in sys.path:
        sys.path.insert(0, str(_path))

CONSUMERS = frozenset({"server", "frontend", "compose", "preflight"})
TYPES = {"str": str, "int": int, "bool": bool, "url": str}
# Building the root reads settings; these let it build without a real database.
GEN_ENV = {"DATABASE_URL": "postgresql://gen@127.0.0.1:9/gen", "ALLOW_DEV_AUTH": "true"}


def _header(kind: str, source: str, comment: str = "#") -> str:
    return (
        f"{comment} GENERATED by scripts/gen.py {kind} from {source} -- do not edit.\n"
    )


def _q(text: str) -> str:
    """A double-quoted literal valid in Python and TypeScript."""
    return json.dumps(text)


# --- settings ---------------------------------------------------------------


def setting_rows(root: Path = ROOT) -> list[dict[str, Any]]:
    data = tomllib.loads((root / "settings.toml").read_text(encoding="utf-8"))
    rows = data.get("setting", [])
    problems: list[str] = []
    seen: set[str] = set()
    for row in rows:
        name = row.get("name", "")
        consumers = set(row.get("consumers", []))
        if not re.fullmatch(r"[A-Z][A-Z0-9_]*", name):
            problems.append(f"{name!r}: name must be UPPER_SNAKE")
        if name in seen:
            problems.append(f"{name}: declared twice")
        seen.add(name)
        kind = row.get("type")
        if kind not in TYPES:
            problems.append(f"{name}: type must be one of {sorted(TYPES)}")
        if not consumers or not consumers <= CONSUMERS:
            problems.append(
                f"{name}: consumers must be a non-empty subset of {sorted(CONSUMERS)}"
            )
        required = bool(row.get("required", False))
        if required and "default" in row:
            problems.append(f"{name}: a required setting takes no default")
        if not required and "default" not in row:
            problems.append(f"{name}: an optional setting needs a default")
        if (
            "default" in row
            and kind in TYPES
            and type(row["default"]) is not TYPES[kind]
        ):
            problems.append(f"{name}: default is not a {kind}")
        if row.get("secret") and "frontend" in consumers:
            problems.append(f"{name}: a secret never reaches the frontend bundle")
        if row.get("secret") and row.get("default", ""):
            problems.append(f"{name}: a secret's default must be empty")
        if required and "server" in consumers and "compose" not in consumers:
            problems.append(
                f"{name}: a required server setting must be forwarded by compose"
            )
        if row.get("test_only") and "compose" in consumers:
            problems.append(
                f"{name}: a test_only setting must not be forwarded by compose"
            )
    if problems:
        raise SystemExit("settings.toml:\n  " + "\n  ".join(problems))
    return sorted(rows, key=lambda r: r["name"])


def _py_default(row: dict[str, Any]) -> str:
    value = row["default"]
    if row.get("secret"):
        return 'SecretStr("")'
    if isinstance(value, bool):
        return "True" if value else "False"
    if isinstance(value, int):
        return str(value)
    return _q(value)


_SETTINGS_PY = '''"""The server's settings, declared once in settings.toml.

load_settings() reads the environment at CALL time, never at import. Secrets are
SecretStr: they do not appear in repr(), in logs or in public_view(). A missing
or malformed setting raises SettingsError naming it -- never printing a value.
"""

from __future__ import annotations

import os
from collections.abc import Mapping

from pydantic import BaseModel, ConfigDict, SecretStr


class SettingsError(ValueError):
    """A setting is missing or malformed. Carries names, never values."""


class Settings(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)

@@FIELDS@@


# (ENV name, field, type, required, secret)
FIELDS: tuple[tuple[str, str, str, bool, bool], ...] = (
@@ROWS@@
)

_TRUE = frozenset({"1", "true", "yes", "on"})
_FALSE = frozenset({"0", "false", "no", "off", ""})


def _coerce(name: str, kind: str, raw: str) -> object:
    if kind == "int":
        try:
            return int(raw)
        except ValueError:
            raise SettingsError(f"{name}: expected an integer") from None
    if kind == "bool":
        word = raw.strip().lower()
        if word in _TRUE:
            return True
        if word in _FALSE:
            return False
        raise SettingsError(f"{name}: expected true or false")
    if kind == "url" and "://" not in raw:
        raise SettingsError(f"{name}: expected a URL")
    return raw


def load_settings(environ: Mapping[str, str] | None = None) -> Settings:
    env = os.environ if environ is None else environ
    values: dict[str, object] = {}
    missing: list[str] = []
    for name, field, kind, required, _secret in FIELDS:
        raw = env.get(name)
        if raw is None or (required and raw == ""):
            if required:
                missing.append(name)
            continue
        values[field] = _coerce(name, kind, raw)
    if missing:
        raise SettingsError("missing required setting(s): " + ", ".join(missing))
    return Settings.model_validate(values)


def public_view(settings: Settings) -> dict[str, object]:
    """Every non-secret setting, for logs and diagnostics."""
    return {
        name: getattr(settings, field)
        for name, field, _kind, _required, secret in FIELDS
        if not secret
    }
'''


def render_settings(root: Path = ROOT) -> dict[Path, str]:
    rows = setting_rows(root)
    server = [r for r in rows if "server" in r["consumers"]]
    fields, table = [], []
    for row in server:
        field = row["name"].lower()
        if row.get("secret"):
            annotation = "SecretStr"
        else:
            annotation = {"str": "str", "url": "str", "int": "int", "bool": "bool"}[
                row["type"]
            ]
        line = f"    {field}: {annotation}"
        if not row.get("required"):
            line += f" = {_py_default(row)}"
        fields.append(line)
        table.append(
            f"    ({_q(row['name'])}, {_q(field)}, {_q(row['type'])}, "
            f"{bool(row.get('required'))}, {bool(row.get('secret'))}),"
        )
    settings_py = _header("settings", "settings.toml") + _SETTINGS_PY.replace(
        "@@FIELDS@@", "\n".join(fields)
    ).replace("@@ROWS@@", "\n".join(table))

    compose = [
        _header("settings", "settings.toml"),
        "# The server service's environment block. A required name uses ${NAME:?} so\n",
        "# compose refuses to start without it instead of passing an empty string.\n",
        "environment:\n",
    ]
    for row in rows:
        if "compose" not in row["consumers"]:
            continue
        name = row["name"]
        if row.get("required"):
            compose.append(f"  {name}: ${{{name}:?{name} is required}}\n")
        else:
            default = row["default"]
            text = (
                ("true" if default else "false")
                if isinstance(default, bool)
                else str(default)
            )
            compose.append(f"  {name}: ${{{name}:-{text}}}\n")

    preflight = [_header("settings", "settings.toml")]
    preflight += [
        f"{row['name']} {'required' if row.get('required') else 'optional'}\n"
        for row in rows
        if "preflight" in row["consumers"]
    ]

    ts = [_header("settings", "settings.toml", "//"), "export const SETTINGS = {\n"]
    for row in rows:
        if "frontend" not in row["consumers"]:
            continue
        ts.append(
            f"  {row['name']}: {{ type: {_q(row['type'])}, default: {_q(str(row['default']))} }},\n"
        )
    ts.append("} as const;\n\n")
    ts.append("export type SettingName = keyof typeof SETTINGS;\n\n")
    ts.append(
        "export function settingText(name: SettingName): string {\n"
        "  const env = import.meta.env as Record<string, string | undefined>;\n"
        "  const raw = env[`VITE_${name}`];\n"
        "  return raw === undefined ? SETTINGS[name].default : raw;\n"
        "}\n\n"
        "export function settingInt(name: SettingName): number {\n"
        "  const value = Number.parseInt(settingText(name), 10);\n"
        "  if (Number.isNaN(value)) throw new Error(`setting ${name} is not an integer`);\n"
        "  return value;\n"
        "}\n"
    )
    return {
        root / "src" / "__app__" / "settings.py": settings_py,
        root / "deploy" / "compose.env.yml": "".join(compose),
        root / "deploy" / "preflight_names.txt": "".join(preflight),
        root / "frontend" / "src" / "gen" / "settings.ts": "".join(ts),
    }


# --- contracts --------------------------------------------------------------


def wire_schemas() -> dict[str, Any]:
    from contracts.wire import MODELS

    models: dict[str, Any] = {}
    for model in MODELS:
        schema = model.model_json_schema(
            mode="validation", ref_template="#/$defs/{model}"
        )
        schema.pop("$defs", None)
        models[model.__name__] = schema
    return {"models": models}


def flat_params(dependant: Any) -> dict[str, list[Any]]:
    """Path, query and body parameters of a route, including its sub-dependencies'."""
    out: dict[str, list[Any]] = {"path": [], "query": [], "body": []}
    seen: set[tuple[str, str]] = set()

    def visit(node: Any) -> None:
        for kind in out:
            for param in getattr(node, f"{kind}_params"):
                if (kind, param.name) not in seen:
                    seen.add((kind, param.name))
                    out[kind].append(param)
        for sub in node.dependencies:
            visit(sub)

    visit(dependant)
    return out


def route_table() -> list[dict[str, Any]]:
    """The composed root's routes -- what the client is generated from."""
    from __app__.roots import api_routes
    from __app__.roots.app import build
    from __app__.settings import load_settings

    comp = build(load_settings(GEN_ENV))
    table = []
    for route in api_routes(comp.app):
        flat = flat_params(route.dependant)
        (method,) = sorted(route.methods or ())
        body = [f.field_info.annotation for f in flat["body"]]
        table.append(
            {
                "name": route.name,
                "method": method,
                "path": route.path,
                "path_params": re.findall(r"{(\w+)}", route.path),
                "query": [
                    (q.name, bool(q.field_info.is_required())) for q in flat["query"]
                ],
                "body": body[0].__name__ if body else None,
                "response": route.response_model.__name__
                if route.response_model
                else None,
            }
        )
    return sorted(table, key=lambda r: r["name"])


def _camel(name: str) -> str:
    head, *rest = name.split("_")
    return head + "".join(part.capitalize() for part in rest)


def ts_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(v) for v in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(ts_type(s) for s in schema["anyOf"])
    kind = schema.get("type")
    if kind == "string":
        return "string"
    if kind in ("integer", "number"):
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "null":
        return "null"
    if kind == "array":
        inner = ts_type(schema["items"])
        return f"({inner})[]" if "|" in inner else f"{inner}[]"
    raise SystemExit(f"gen contracts: no TypeScript mapping for {schema}")


def render_contracts(root: Path = ROOT) -> dict[Path, str]:
    frozen = wire_schemas()
    frozen_text = json.dumps(frozen, indent=2, sort_keys=True) + "\n"
    models = json.loads(frozen_text)["models"]

    types = [_header("contracts", "wire/frozen.json", "//")]
    for name, schema in models.items():
        required = set(schema.get("required", []))
        types.append(f"\nexport interface {name} {{\n")
        for prop, prop_schema in schema.get("properties", {}).items():
            optional = "" if prop in required else "?"
            types.append(f"  {prop}{optional}: {ts_type(prop_schema)};\n")
        types.append("}\n")

    routes = route_table()
    used = sorted(
        {r["response"] for r in routes if r["response"]}
        | {r["body"] for r in routes if r["body"]}
    )
    client = [
        _header("contracts", "the composed root's route table", "//"),
        'import type { Transport } from "../lib/client";\n',
        f'import type {{ {", ".join(used)} }} from "./types";\n\n',
        "export interface Api {\n",
    ]
    impl = []
    for r in routes:
        fn = _camel(r["name"])
        params = [f"{p}: string" for p in r["path_params"]]
        args = list(r["path_params"])
        if r["query"]:
            fields = "; ".join(
                f"{q}{'' if req else '?'}: string" for q, req in r["query"]
            )
            all_optional = not any(req for _q, req in r["query"])
            params.append(f"query{'?' if all_optional else ''}: {{ {fields} }}")
            args.append("query = {}" if all_optional else "query")
        if r["body"]:
            params.append(f"body: {r['body']}")
            args.append("body")
        client.append(f"  {fn}({', '.join(params)}): Promise<{r['response']}>;\n")
        path = r["path"]
        for p in r["path_params"]:
            path = path.replace("{" + p + "}", "${encodeURIComponent(" + p + ")}")
        options = [
            k
            for k in ("query", "body")
            if (k == "query" and r["query"]) or (k == "body" and r["body"])
        ]
        tail = f", {{ {', '.join(options)} }}" if options else ""
        impl.append(
            f"    {fn}: ({', '.join(args)}) =>\n"
            f'      transport.request<{r["response"]}>("{r["method"]}", `{path}`{tail}),\n'
        )
    client.append("}\n\n")
    client.append("export function makeApi(transport: Transport): Api {\n  return {\n")
    client.extend(impl)
    client.append("  };\n}\n\n")
    client.append("export const ROUTES = [\n")
    for r in routes:
        client.append(
            f'  {{ name: "{_camel(r["name"])}", method: "{r["method"]}", path: "{r["path"]}" }},\n'
        )
    client.append("] as const;\n")
    return {
        root / "wire" / "frozen.json": frozen_text,
        root / "frontend" / "src" / "gen" / "types.ts": "".join(types),
        root / "frontend" / "src" / "gen" / "client.ts": "".join(client),
    }


# --- concepts and registry --------------------------------------------------


def render_concepts(root: Path = ROOT) -> dict[Path, str]:
    data = tomllib.loads((root / "concepts.toml").read_text(encoding="utf-8"))
    lines = [
        _header("concepts", "concepts.toml", "//"),
        'export type Unit = "cents" | "count";\n\n',
        "export const CONCEPTS = {\n",
    ]
    for concept in sorted(data.get("concept", []), key=lambda c: c["name"]):
        lines.append(f"  {concept['name']}: {{ unit: {_q(concept['unit'])} }},\n")
    lines.append("} as const satisfies Record<string, { unit: Unit }>;\n\n")
    lines.append("export type Concept = keyof typeof CONCEPTS;\n")
    return {root / "frontend" / "src" / "gen" / "concepts.ts": "".join(lines)}


def render_registry(root: Path = ROOT) -> dict[Path, str]:
    from contracts import registry

    lines = [
        _header("registry", "contracts/registry.py", "//"),
        "export const SCREEN_STATES = [\n",
    ]
    lines += [f"  {_q(state)},\n" for state in registry.SCREEN_STATES]
    lines.append("] as const;\n\n")
    lines.append("export type ScreenState = (typeof SCREEN_STATES)[number];\n")
    return {root / "frontend" / "src" / "gen" / "registry.ts": "".join(lines)}


RENDERERS = {
    "settings": render_settings,
    "contracts": render_contracts,
    "concepts": render_concepts,
    "registry": render_registry,
}


def stale(rendered: dict[Path, str]) -> list[Path]:
    """Files whose content on disk differs from `rendered` (line endings ignored)."""
    out = []
    for path, text in rendered.items():
        current = (
            path.read_text(encoding="utf-8").replace("\r\n", "\n")
            if path.exists()
            else None
        )
        if current != text:
            out.append(path)
    return out


def _controls(check: bool, root: Path = ROOT) -> int:
    node = shutil.which("node")
    if node is None:
        print("gen controls: node not found; install Node 22", file=sys.stderr)
        return 1
    argv = [node, str(root / "frontend" / "scripts" / "gen-controls.mjs")]
    return subprocess.run(
        argv + (["--check"] if check else []), cwd=root / "frontend"
    ).returncode


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="scripts/gen.py")
    parser.add_argument("what", choices=[*RENDERERS, "controls", "all"])
    parser.add_argument(
        "--check", action="store_true", help="write nothing; exit 1 on drift"
    )
    args = parser.parse_args(argv)
    kinds = (
        [*RENDERERS]
        if args.what == "all"
        else [args.what]
        if args.what in RENDERERS
        else []
    )
    bad = 0
    for kind in kinds:
        rendered = RENDERERS[kind](ROOT)
        if args.check:
            for path in stale(rendered):
                print(
                    f"stale: {path.relative_to(ROOT).as_posix()} (run scripts/gen.py {kind})"
                )
                bad = 1
            continue
        for path, text in rendered.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            with open(path, "w", encoding="utf-8", newline="\n") as handle:
                handle.write(text)
            print(f"wrote {path.relative_to(ROOT).as_posix()}")
    if args.what in ("controls", "all"):
        bad |= _controls(args.check)
    return bad


if __name__ == "__main__":
    raise SystemExit(main())
